# Site settings
title: Intentional Group
email: info@intentional.ae
description: >-
  The Intentional Group - Building Excellence in Education, Property Development, Landscaping, and Design & Build Interiors
baseurl: "/intentional"
url: "https://scottfeltham.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  businesses:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "businesses"
    values:
      layout: "business"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
